foreach(ECONOMIA_REQUIRED_VAR
        WINDEPLOYQT_EXECUTABLE
        QTPATHS_EXECUTABLE
        TARGET_FILE
        RUNTIME_DIR
        PLUGIN_DIR
        TRANSLATION_DIR)
    if(NOT DEFINED ${ECONOMIA_REQUIRED_VAR})
        message(FATAL_ERROR "${ECONOMIA_REQUIRED_VAR} was not provided")
    endif()
endforeach()

file(TO_CMAKE_PATH "${WINDEPLOYQT_EXECUTABLE}" WINDEPLOYQT_EXECUTABLE_NORMALIZED)
file(TO_CMAKE_PATH "${QTPATHS_EXECUTABLE}" QTPATHS_EXECUTABLE_NORMALIZED)
file(TO_CMAKE_PATH "${TARGET_FILE}" TARGET_FILE_NORMALIZED)
file(TO_CMAKE_PATH "${RUNTIME_DIR}" RUNTIME_DIR_NORMALIZED)
file(TO_CMAKE_PATH "${PLUGIN_DIR}" PLUGIN_DIR_NORMALIZED)
file(TO_CMAKE_PATH "${TRANSLATION_DIR}" TRANSLATION_DIR_NORMALIZED)

if(NOT EXISTS "${TARGET_FILE_NORMALIZED}")
    message(STATUS "Optional Qt dependency target not found, skipping deploy: ${TARGET_FILE_NORMALIZED}")
    return()
endif()

if(NOT EXISTS "${WINDEPLOYQT_EXECUTABLE_NORMALIZED}" OR NOT EXISTS "${QTPATHS_EXECUTABLE_NORMALIZED}")
    message(WARNING "windeployqt.exe or qtpaths6.exe was not found. Skipping Qt dependency deploy for ${TARGET_FILE_NORMALIZED}.")
    return()
endif()

file(MAKE_DIRECTORY "${RUNTIME_DIR_NORMALIZED}")
file(MAKE_DIRECTORY "${PLUGIN_DIR_NORMALIZED}")
file(MAKE_DIRECTORY "${TRANSLATION_DIR_NORMALIZED}")

get_filename_component(ECONOMIA_TARGET_NAME "${TARGET_FILE_NORMALIZED}" NAME_WE)
get_filename_component(ECONOMIA_TARGET_SUFFIX "${TARGET_FILE_NORMALIZED}" EXT)
if(DEFINED ENV{TEMP} AND NOT "$ENV{TEMP}" STREQUAL "")
    set(ECONOMIA_STAGING_ROOT "$ENV{TEMP}")
elseif(DEFINED ENV{TMP} AND NOT "$ENV{TMP}" STREQUAL "")
    set(ECONOMIA_STAGING_ROOT "$ENV{TMP}")
else()
    set(ECONOMIA_STAGING_ROOT "${RUNTIME_DIR_NORMALIZED}")
endif()

set(ECONOMIA_STAGING_DIR "${ECONOMIA_STAGING_ROOT}/qtdeploy_staging/${ECONOMIA_TARGET_NAME}")
set(ECONOMIA_STAGING_TARGET_FILE "${ECONOMIA_STAGING_DIR}/${ECONOMIA_TARGET_NAME}${ECONOMIA_TARGET_SUFFIX}")

file(MAKE_DIRECTORY "${ECONOMIA_STAGING_DIR}")
file(COPY_FILE "${TARGET_FILE_NORMALIZED}" "${ECONOMIA_STAGING_TARGET_FILE}" ONLY_IF_DIFFERENT)

set(ECONOMIA_DEPLOY_COMMAND
    "${WINDEPLOYQT_EXECUTABLE_NORMALIZED}"
    "${ECONOMIA_STAGING_TARGET_FILE}"
    --dir "${RUNTIME_DIR_NORMALIZED}"
    --libdir "${RUNTIME_DIR_NORMALIZED}"
    --plugindir "${PLUGIN_DIR_NORMALIZED}"
    --translationdir "${TRANSLATION_DIR_NORMALIZED}"
)

if(DEFINED NO_COMPILER_RUNTIME AND NO_COMPILER_RUNTIME)
    list(APPEND ECONOMIA_DEPLOY_COMMAND --no-compiler-runtime)
else()
    list(APPEND ECONOMIA_DEPLOY_COMMAND --compiler-runtime)
endif()

if(DEFINED QT_TRANSLATIONS AND NOT "${QT_TRANSLATIONS}" STREQUAL "")
    list(APPEND ECONOMIA_DEPLOY_COMMAND --translations "${QT_TRANSLATIONS}")
else()
    list(APPEND ECONOMIA_DEPLOY_COMMAND --no-translations)
endif()

list(APPEND ECONOMIA_DEPLOY_COMMAND --qtpaths "${QTPATHS_EXECUTABLE_NORMALIZED}")

set(ECONOMIA_DEPLOY_RESULT 1)
foreach(ECONOMIA_DEPLOY_ATTEMPT RANGE 1 5)
    execute_process(
        COMMAND ${ECONOMIA_DEPLOY_COMMAND}
        RESULT_VARIABLE ECONOMIA_DEPLOY_RESULT
    )

    if(ECONOMIA_DEPLOY_RESULT EQUAL 0)
        break()
    endif()

    if(ECONOMIA_DEPLOY_ATTEMPT LESS 5)
        execute_process(COMMAND "${CMAKE_COMMAND}" -E sleep 1)
    endif()
endforeach()

if(NOT ECONOMIA_DEPLOY_RESULT EQUAL 0)
    message(FATAL_ERROR "windeployqt failed for ${TARGET_FILE_NORMALIZED} with exit code ${ECONOMIA_DEPLOY_RESULT}")
endif()

file(REMOVE "${ECONOMIA_STAGING_TARGET_FILE}")
file(REMOVE_RECURSE "${ECONOMIA_STAGING_DIR}")

if(DEFINED NO_COMPILER_RUNTIME AND NO_COMPILER_RUNTIME)
    file(GLOB ECONOMIA_COMPILER_RUNTIME_INSTALLERS
        "${RUNTIME_DIR_NORMALIZED}/vc_redist*.exe"
        "${RUNTIME_DIR_NORMALIZED}/vcredist*.exe"
    )
    if(ECONOMIA_COMPILER_RUNTIME_INSTALLERS)
        file(REMOVE ${ECONOMIA_COMPILER_RUNTIME_INSTALLERS})
    endif()
endif()

message(STATUS "Deployed shared Qt dependencies for: ${TARGET_FILE_NORMALIZED}")
