if(NOT DEFINED DEPLOY_ROOT)
    message(FATAL_ERROR "DEPLOY_ROOT was not provided")
endif()

file(TO_CMAKE_PATH "${DEPLOY_ROOT}" DEPLOY_ROOT_NORMALIZED)
if(NOT EXISTS "${DEPLOY_ROOT_NORMALIZED}")
    return()
endif()

set(ECONOMIA_OPTIONAL_ROOT_RUNTIME_PATTERNS
    "concrt140*.dll"
    "vcomp140*.dll"
    "vcruntime140_threads*.dll"
    "msvcp140_atomic_wait*.dll"
    "msvcp140_codecvt_ids*.dll"
    "D3Dcompiler_*.dll"
    "d3dcompiler_*.dll"
    "dxcompiler.dll"
    "dxil.dll"
    "opengl32sw.dll"
)

if(PRUNE_MSVC_RUNTIME)
    list(APPEND ECONOMIA_OPTIONAL_ROOT_RUNTIME_PATTERNS
        "msvcp140*.dll"
        "vcruntime140*.dll"
    )
endif()

set(ECONOMIA_OPTIONAL_ROOT_RUNTIME_FILES)
foreach(ECONOMIA_OPTIONAL_ROOT_RUNTIME_PATTERN IN LISTS ECONOMIA_OPTIONAL_ROOT_RUNTIME_PATTERNS)
    file(GLOB ECONOMIA_OPTIONAL_ROOT_RUNTIME_MATCHES
        "${DEPLOY_ROOT_NORMALIZED}/${ECONOMIA_OPTIONAL_ROOT_RUNTIME_PATTERN}"
    )
    list(APPEND ECONOMIA_OPTIONAL_ROOT_RUNTIME_FILES ${ECONOMIA_OPTIONAL_ROOT_RUNTIME_MATCHES})
endforeach()

list(REMOVE_DUPLICATES ECONOMIA_OPTIONAL_ROOT_RUNTIME_FILES)
if(ECONOMIA_OPTIONAL_ROOT_RUNTIME_FILES)
    file(REMOVE ${ECONOMIA_OPTIONAL_ROOT_RUNTIME_FILES})
    list(LENGTH ECONOMIA_OPTIONAL_ROOT_RUNTIME_FILES ECONOMIA_OPTIONAL_ROOT_RUNTIME_FILE_COUNT)
    message(STATUS "Pruned ${ECONOMIA_OPTIONAL_ROOT_RUNTIME_FILE_COUNT} optional root runtime DLL(s) from: ${DEPLOY_ROOT_NORMALIZED}")
endif()
